/**
 * Domain types for the multichain AA trading layer.
 *
 * These types are chain-agnostic and define the core data structures
 * used by the trading system.
 */

/** Intent to swap tokens — generated by the LLM agent */
export interface SwapIntent {
  userId: number;
  chainId: number;
  tokenIn: string;
  tokenOut: string;
  amountIn: bigint;
  minAmountOut: bigint;
  slippageBps: number;
}

/** Result of a trade execution */
export interface TradeResult {
  txHash: string;
  userOpHash: string;
  amountIn: bigint;
  amountOut: bigint;
  feeAmount: bigint;
  gasCostUsd: bigint;
  status: 'success' | 'failed';
  timestamp: number;
}

/** Session key — limited permissions granted to the trading agent */
export interface SessionKey {
  address: string;
  maxPerTrade: bigint;
  dailyLimit: bigint;
  expiresAt: number;
  allowedTokens: string[];
}

/** ERC-4337 UserOperation — the atomic unit of AA execution */
export interface UserOperation {
  sender: string;
  nonce: bigint;
  initCode: string;
  callData: string;
  callGasLimit: bigint;
  verificationGasLimit: bigint;
  preVerificationGas: bigint;
  maxFeePerGas: bigint;
  maxPriorityFeePerGas: bigint;
  paymasterAndData: string;
  signature: string;
}

/** Result of a UserOperation execution */
export interface UserOpResult {
  userOpHash: string;
  txHash: string;
  status: 'success' | 'failed';
  gasUsed: bigint;
  gasPrice: bigint;
  logs: Array<{
    address: string;
    topics: string[];
    data: string;
  }>;
}

/** DEX quote for a swap path */
export interface Quote {
  amountOut: bigint;
  priceImpact: number;
  route: string[];
  gasEstimate: bigint;
}

/** Parameters for requesting a DEX quote */
export interface QuoteParams {
  chainId: number;
  tokenIn: string;
  tokenOut: string;
  amountIn: bigint;
  slippageBps: number;
}

/** Encoded EVM call ready for execution */
export interface EncodedCall {
  to: string;
  data: string;
  value: bigint;
}

/** EVM call structure for SmartWallet.execute() */
export interface EvmCall {
  to: string;
  data: string;
  value?: bigint;
}

/** Paymaster data for UserOperation gas sponsorship */
export interface PaymasterData {
  paymaster: string;
  paymasterData: string;
  paymasterVerificationGasLimit: bigint;
  paymasterPostOpGasLimit: bigint;
}

/** Gas estimation for a UserOperation */
export interface GasEstimate {
  callGasLimit: bigint;
  verificationGasLimit: bigint;
  preVerificationGas: bigint;
}
